/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1gestionbv (void)
{
  GtkWidget *window1gestionbv;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *buttongestionbvsupprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *afficher1;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label27;
  GtkWidget *buttongestinbvajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *buttongestinbvmodifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *entry_recherche_bv;
  GtkWidget *label31;
  GtkWidget *label29;
  GtkWidget *button_recherche_bv;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label30;
  GtkWidget *buttonretourgestionbv;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label25;
  GtkWidget *button_stat;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label32;

  window1gestionbv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1gestionbv, 760, 600);
  gtk_window_set_title (GTK_WINDOW (window1gestionbv), _("gestiondebuv"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1gestionbv), fixed1);
  gtk_widget_set_size_request (fixed1, 760, 600);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 64, 160);
  gtk_widget_set_size_request (treeview1, 568, 304);

  buttongestionbvsupprimer = gtk_button_new ();
  gtk_widget_show (buttongestionbvsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongestionbvsupprimer, 640, 392);
  gtk_widget_set_size_request (buttongestionbvsupprimer, 112, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttongestionbvsupprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  afficher1 = gtk_button_new ();
  gtk_widget_show (afficher1);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher1, 640, 160);
  gtk_widget_set_size_request (afficher1, 112, 64);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (afficher1), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox9), label27, FALSE, FALSE, 0);

  buttongestinbvajouter = gtk_button_new ();
  gtk_widget_show (buttongestinbvajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongestinbvajouter, 640, 240);
  gtk_widget_set_size_request (buttongestinbvajouter, 112, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttongestinbvajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  buttongestinbvmodifier = gtk_button_new ();
  gtk_widget_show (buttongestinbvmodifier);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongestinbvmodifier, 640, 320);
  gtk_widget_set_size_request (buttongestinbvmodifier, 112, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttongestinbvmodifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  entry_recherche_bv = gtk_entry_new ();
  gtk_widget_show (entry_recherche_bv);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_recherche_bv, 464, 80);
  gtk_widget_set_size_request (entry_recherche_bv, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche_bv), 8226);

  label31 = gtk_label_new (_("entry Id :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed1), label31, 448, 40);
  gtk_widget_set_size_request (label31, 120, 25);

  label29 = gtk_label_new (_("Gestion de bureau"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed1), label29, 120, 16);
  gtk_widget_set_size_request (label29, 280, 64);

  button_recherche_bv = gtk_button_new ();
  gtk_widget_show (button_recherche_bv);
  gtk_fixed_put (GTK_FIXED (fixed1), button_recherche_bv, 640, 72);
  gtk_widget_set_size_request (button_recherche_bv, 112, 64);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_recherche_bv), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox10), label30, FALSE, FALSE, 0);

  buttonretourgestionbv = gtk_button_new ();
  gtk_widget_show (buttonretourgestionbv);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonretourgestionbv, 280, 528);
  gtk_widget_set_size_request (buttonretourgestionbv, 122, 61);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonretourgestionbv), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox8), label25, FALSE, FALSE, 0);

  button_stat = gtk_button_new ();
  gtk_widget_show (button_stat);
  gtk_fixed_put (GTK_FIXED (fixed1), button_stat, 640, 472);
  gtk_widget_set_size_request (button_stat, 112, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_stat), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox11), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttongestionbvsupprimer, "clicked",
                    G_CALLBACK (on_buttongestionbvsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher1, "clicked",
                    G_CALLBACK (on_afficher1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongestinbvajouter, "clicked",
                    G_CALLBACK (on_buttongestinbvajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongestinbvmodifier, "clicked",
                    G_CALLBACK (on_buttongestinbvmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_recherche_bv, "clicked",
                    G_CALLBACK (on_button_recherche_bv_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourgestionbv, "clicked",
                    G_CALLBACK (on_buttonretourgestionbv_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_stat, "clicked",
                    G_CALLBACK (on_button_stat_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1gestionbv, window1gestionbv, "window1gestionbv");
  GLADE_HOOKUP_OBJECT (window1gestionbv, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, buttongestionbvsupprimer, "buttongestionbvsupprimer");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1gestionbv, afficher1, "afficher1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1gestionbv, buttongestinbvajouter, "buttongestinbvajouter");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1gestionbv, buttongestinbvmodifier, "buttongestinbvmodifier");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1gestionbv, entry_recherche_bv, "entry_recherche_bv");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label31, "label31");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label29, "label29");
  GLADE_HOOKUP_OBJECT (window1gestionbv, button_recherche_bv, "button_recherche_bv");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label30, "label30");
  GLADE_HOOKUP_OBJECT (window1gestionbv, buttonretourgestionbv, "buttonretourgestionbv");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1gestionbv, button_stat, "button_stat");
  GLADE_HOOKUP_OBJECT (window1gestionbv, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1gestionbv, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1gestionbv, image11, "image11");
  GLADE_HOOKUP_OBJECT (window1gestionbv, label32, "label32");

  return window1gestionbv;
}

GtkWidget*
create_window2ajouterbv (void)
{
  GtkWidget *window2ajouterbv;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *labelajouteridentifiant;
  GtkWidget *labelajoutercapaciter;
  GtkWidget *labelajouterdate;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label12;
  GtkWidget *radiobuttonajouter20;
  GSList *radiobuttonajouter20_group = NULL;
  GtkWidget *radiobuttonajouter10;
  GtkWidget *buttonajouterok;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *button_retour_ajouter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label11;
  GtkWidget *comboboxentry1;
  GtkWidget *label32_numbureau;
  GtkWidget *label33_id;
  GtkWidget *e_id_bv;
  GtkWidget *labelajouternumerovote;
  GtkWidget *radiobuttonajouter40;

  window2ajouterbv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2ajouterbv), _("Ajouter bv"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2ajouterbv), fixed2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 336, 80);
  gtk_widget_set_size_request (fixed3, 50, 50);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 192, 80);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 192, 152);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  labelajouteridentifiant = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelajouteridentifiant);
  gtk_fixed_put (GTK_FIXED (fixed2), labelajouteridentifiant, 24, 144);
  gtk_widget_set_size_request (labelajouteridentifiant, 136, 40);

  labelajoutercapaciter = gtk_label_new (_("Capacit\303\251"));
  gtk_widget_show (labelajoutercapaciter);
  gtk_fixed_put (GTK_FIXED (fixed2), labelajoutercapaciter, 24, 208);
  gtk_widget_set_size_request (labelajoutercapaciter, 136, 64);

  labelajouterdate = gtk_label_new (_("Date de vote "));
  gtk_widget_show (labelajouterdate);
  gtk_fixed_put (GTK_FIXED (fixed2), labelajouterdate, 16, 272);
  gtk_widget_set_size_request (labelajouterdate, 104, 64);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 184, 288);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 0, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 456, 288);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label12 = gtk_label_new (_("Ajouter bureau de vote "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 216, 16);
  gtk_widget_set_size_request (label12, 224, 48);

  radiobuttonajouter20 = gtk_radio_button_new_with_mnemonic (NULL, _("20"));
  gtk_widget_show (radiobuttonajouter20);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonajouter20, 320, 232);
  gtk_widget_set_size_request (radiobuttonajouter20, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonajouter20), radiobuttonajouter20_group);
  radiobuttonajouter20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonajouter20));

  radiobuttonajouter10 = gtk_radio_button_new_with_mnemonic (NULL, _("10"));
  gtk_widget_show (radiobuttonajouter10);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonajouter10, 472, 232);
  gtk_widget_set_size_request (radiobuttonajouter10, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonajouter10), radiobuttonajouter20_group);
  radiobuttonajouter20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonajouter10));

  buttonajouterok = gtk_button_new ();
  gtk_widget_show (buttonajouterok);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonajouterok, 136, 376);
  gtk_widget_set_size_request (buttonajouterok, 136, 72);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonajouterok), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("ok "));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  button_retour_ajouter = gtk_button_new ();
  gtk_widget_show (button_retour_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_ajouter, 296, 376);
  gtk_widget_set_size_request (button_retour_ajouter, 136, 72);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_retour_ajouter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry1, 256, 288);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("novembre "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("decembre "));

  label32_numbureau = gtk_label_new (_(" <span foreground=\"red\"><b>champ vide!!!!!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label32_numbureau, 352, 80);
  gtk_widget_set_size_request (label32_numbureau, 168, 32);
  gtk_label_set_use_markup (GTK_LABEL (label32_numbureau), TRUE);

  label33_id = gtk_label_new (_(" <span foreground=\"red\"><b>champ vide!!!!!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), label33_id, 416, 152);
  gtk_widget_set_size_request (label33_id, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (label33_id), TRUE);

  e_id_bv = gtk_label_new (_(" <span foreground=\"red\"><b>ID existe!!!!!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed2), e_id_bv, 360, 136);
  gtk_widget_set_size_request (e_id_bv, 104, 56);
  gtk_label_set_use_markup (GTK_LABEL (e_id_bv), TRUE);

  labelajouternumerovote = gtk_label_new (_("Num\303\251ro de bureau"));
  gtk_widget_show (labelajouternumerovote);
  gtk_fixed_put (GTK_FIXED (fixed2), labelajouternumerovote, 0, 72);
  gtk_widget_set_size_request (labelajouternumerovote, 192, 40);

  radiobuttonajouter40 = gtk_radio_button_new_with_mnemonic (NULL, _("40"));
  gtk_widget_show (radiobuttonajouter40);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonajouter40, 176, 232);
  gtk_widget_set_size_request (radiobuttonajouter40, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonajouter40), radiobuttonajouter20_group);
  radiobuttonajouter20_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonajouter40));

  g_signal_connect ((gpointer) radiobuttonajouter20, "toggled",
                    G_CALLBACK (on_radiobuttonajouter20_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonajouter10, "toggled",
                    G_CALLBACK (on_radiobuttonajouter10_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonajouterok, "clicked",
                    G_CALLBACK (on_buttonajouterok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajouter, "clicked",
                    G_CALLBACK (on_button_retour_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonajouter40, "toggled",
                    G_CALLBACK (on_radiobuttonajouter40_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2ajouterbv, window2ajouterbv, "window2ajouterbv");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, labelajouteridentifiant, "labelajouteridentifiant");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, labelajoutercapaciter, "labelajoutercapaciter");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, labelajouterdate, "labelajouterdate");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, radiobuttonajouter20, "radiobuttonajouter20");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, radiobuttonajouter10, "radiobuttonajouter10");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, buttonajouterok, "buttonajouterok");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, image4, "image4");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, button_retour_ajouter, "button_retour_ajouter");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, image5, "image5");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, label32_numbureau, "label32_numbureau");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, label33_id, "label33_id");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, e_id_bv, "e_id_bv");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, labelajouternumerovote, "labelajouternumerovote");
  GLADE_HOOKUP_OBJECT (window2ajouterbv, radiobuttonajouter40, "radiobuttonajouter40");

  return window2ajouterbv;
}

GtkWidget*
create_window3modifier__bv (void)
{
  GtkWidget *window3modifier__bv;
  GtkWidget *fixed5;
  GtkWidget *fixed6;
  GtkWidget *entry3;
  GtkWidget *labelmodifiercapacit__;
  GtkWidget *label22;
  GtkWidget *buttonok_modifier;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label23;
  GtkWidget *buttonannuler_modifier;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label24;
  GtkWidget *label26;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *labelmodifiernumerodebureau;
  GtkWidget *labelmodifierididentifiant;
  GtkWidget *label28;
  GtkWidget *radiobutton_modif1;
  GSList *radiobutton_modif1_group = NULL;
  GtkWidget *radiobutton_modif2;
  GtkWidget *radiobutton_modif3;
  GtkWidget *checkbutton_modif1;
  GtkWidget *comboboxentry2;

  window3modifier__bv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3modifier__bv), _("modifier bv"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window3modifier__bv), fixed5);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 336, 80);
  gtk_widget_set_size_request (fixed6, 50, 50);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 192, 136);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  labelmodifiercapacit__ = gtk_label_new (_("Capacit\303\251"));
  gtk_widget_show (labelmodifiercapacit__);
  gtk_fixed_put (GTK_FIXED (fixed5), labelmodifiercapacit__, 24, 208);
  gtk_widget_set_size_request (labelmodifiercapacit__, 136, 64);

  label22 = gtk_label_new (_("Modifier bureau de vote "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 216, 16);
  gtk_widget_set_size_request (label22, 224, 48);

  buttonok_modifier = gtk_button_new ();
  gtk_widget_show (buttonok_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonok_modifier, 176, 408);
  gtk_widget_set_size_request (buttonok_modifier, 112, 64);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonok_modifier), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox6), label23, FALSE, FALSE, 0);

  buttonannuler_modifier = gtk_button_new ();
  gtk_widget_show (buttonannuler_modifier);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonannuler_modifier, 352, 408);
  gtk_widget_set_size_request (buttonannuler_modifier, 128, 64);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonannuler_modifier), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox7), label24, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("Date Modification"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 40, 296);
  gtk_widget_set_size_request (label26, 128, 32);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton4, 224, 296);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 2050, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton5, 520, 296);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  labelmodifiernumerodebureau = gtk_label_new (_("Num\303\251ro de bureau"));
  gtk_widget_show (labelmodifiernumerodebureau);
  gtk_fixed_put (GTK_FIXED (fixed5), labelmodifiernumerodebureau, 0, 128);
  gtk_widget_set_size_request (labelmodifiernumerodebureau, 192, 40);

  labelmodifierididentifiant = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelmodifierididentifiant);
  gtk_fixed_put (GTK_FIXED (fixed5), labelmodifierididentifiant, 32, 80);
  gtk_widget_set_size_request (labelmodifierididentifiant, 136, 40);

  label28 = gtk_label_new ("");
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 208, 80);
  gtk_widget_set_size_request (label28, 168, 32);

  radiobutton_modif1 = gtk_radio_button_new_with_mnemonic (NULL, _("40"));
  gtk_widget_show (radiobutton_modif1);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_modif1, 176, 224);
  gtk_widget_set_size_request (radiobutton_modif1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modif1), radiobutton_modif1_group);
  radiobutton_modif1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modif1));

  radiobutton_modif2 = gtk_radio_button_new_with_mnemonic (NULL, _("20"));
  gtk_widget_show (radiobutton_modif2);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_modif2, 272, 224);
  gtk_widget_set_size_request (radiobutton_modif2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modif2), radiobutton_modif1_group);
  radiobutton_modif1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modif2));

  radiobutton_modif3 = gtk_radio_button_new_with_mnemonic (NULL, _("10"));
  gtk_widget_show (radiobutton_modif3);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_modif3, 384, 224);
  gtk_widget_set_size_request (radiobutton_modif3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modif3), radiobutton_modif1_group);
  radiobutton_modif1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modif3));

  checkbutton_modif1 = gtk_check_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (checkbutton_modif1);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton_modif1, 248, 352);
  gtk_widget_set_size_request (checkbutton_modif1, 118, 24);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry2, 304, 296);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("novembre "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("decembre "));

  g_signal_connect ((gpointer) buttonok_modifier, "clicked",
                    G_CALLBACK (on_buttonok_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonannuler_modifier, "clicked",
                    G_CALLBACK (on_buttonannuler_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modif1, "toggled",
                    G_CALLBACK (on_radiobutton_modif1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modif2, "toggled",
                    G_CALLBACK (on_radiobutton_modif2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modif3, "toggled",
                    G_CALLBACK (on_radiobutton_modif3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_modif1, "toggled",
                    G_CALLBACK (on_checkbutton_modif1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3modifier__bv, window3modifier__bv, "window3modifier__bv");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, labelmodifiercapacit__, "labelmodifiercapacit__");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, label22, "label22");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, buttonok_modifier, "buttonok_modifier");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, image6, "image6");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, label23, "label23");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, buttonannuler_modifier, "buttonannuler_modifier");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, image7, "image7");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, label24, "label24");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, label26, "label26");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, labelmodifiernumerodebureau, "labelmodifiernumerodebureau");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, labelmodifierididentifiant, "labelmodifierididentifiant");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, label28, "label28");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, radiobutton_modif1, "radiobutton_modif1");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, radiobutton_modif2, "radiobutton_modif2");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, radiobutton_modif3, "radiobutton_modif3");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, checkbutton_modif1, "checkbutton_modif1");
  GLADE_HOOKUP_OBJECT (window3modifier__bv, comboboxentry2, "comboboxentry2");

  return window3modifier__bv;
}

GtkWidget*
create_window4_stat (void)
{
  GtkWidget *window4_stat;
  GtkWidget *fixed7;
  GtkWidget *label34;
  GtkWidget *label33;
  GtkWidget *button_taux_obs;
  GtkWidget *label_te;
  GtkWidget *label_tn;
  GtkWidget *button_retour_stat;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label35;
  GtkWidget *treeview_candidat_gagne;
  GtkWidget *button1_afficher_stat_gagne;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label37;
  GtkWidget *label36;

  window4_stat = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window4_stat, 800, 600);
  gtk_window_set_title (GTK_WINDOW (window4_stat), _("window_stat"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window4_stat), fixed7);
  gtk_widget_set_size_request (fixed7, 800, 600);

  label34 = gtk_label_new (_("taux etranger"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 152, 136);
  gtk_widget_set_size_request (label34, 96, 32);

  label33 = gtk_label_new (_("taux nationaux "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 8, 136);
  gtk_widget_set_size_request (label33, 112, 33);

  button_taux_obs = gtk_button_new_with_mnemonic (_("taux des observateurs"));
  gtk_widget_show (button_taux_obs);
  gtk_fixed_put (GTK_FIXED (fixed7), button_taux_obs, 24, 64);
  gtk_widget_set_size_request (button_taux_obs, 160, 48);

  label_te = gtk_label_new ("");
  gtk_widget_show (label_te);
  gtk_fixed_put (GTK_FIXED (fixed7), label_te, 144, 184);
  gtk_widget_set_size_request (label_te, 104, 40);

  label_tn = gtk_label_new ("");
  gtk_widget_show (label_tn);
  gtk_fixed_put (GTK_FIXED (fixed7), label_tn, 24, 192);
  gtk_widget_set_size_request (label_tn, 80, 32);

  button_retour_stat = gtk_button_new ();
  gtk_widget_show (button_retour_stat);
  gtk_fixed_put (GTK_FIXED (fixed7), button_retour_stat, 304, 520);
  gtk_widget_set_size_request (button_retour_stat, 120, 56);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_retour_stat), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox12), label35, FALSE, FALSE, 0);

  treeview_candidat_gagne = gtk_tree_view_new ();
  gtk_widget_show (treeview_candidat_gagne);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview_candidat_gagne, 488, 192);
  gtk_widget_set_size_request (treeview_candidat_gagne, 300, 200);

  button1_afficher_stat_gagne = gtk_button_new ();
  gtk_widget_show (button1_afficher_stat_gagne);
  gtk_fixed_put (GTK_FIXED (fixed7), button1_afficher_stat_gagne, 544, 128);
  gtk_widget_set_size_request (button1_afficher_stat_gagne, 152, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button1_afficher_stat_gagne), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox13), label37, FALSE, FALSE, 0);

  label36 = gtk_label_new (_("Candidats Gangnant"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 504, 56);
  gtk_widget_set_size_request (label36, 256, 56);

  g_signal_connect ((gpointer) button_taux_obs, "clicked",
                    G_CALLBACK (on_button_taux_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_stat, "clicked",
                    G_CALLBACK (on_button_retour_stat_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_afficher_stat_gagne, "clicked",
                    G_CALLBACK (on_button1_afficher_stat_gagne_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4_stat, window4_stat, "window4_stat");
  GLADE_HOOKUP_OBJECT (window4_stat, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window4_stat, label34, "label34");
  GLADE_HOOKUP_OBJECT (window4_stat, label33, "label33");
  GLADE_HOOKUP_OBJECT (window4_stat, button_taux_obs, "button_taux_obs");
  GLADE_HOOKUP_OBJECT (window4_stat, label_te, "label_te");
  GLADE_HOOKUP_OBJECT (window4_stat, label_tn, "label_tn");
  GLADE_HOOKUP_OBJECT (window4_stat, button_retour_stat, "button_retour_stat");
  GLADE_HOOKUP_OBJECT (window4_stat, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window4_stat, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window4_stat, image12, "image12");
  GLADE_HOOKUP_OBJECT (window4_stat, label35, "label35");
  GLADE_HOOKUP_OBJECT (window4_stat, treeview_candidat_gagne, "treeview_candidat_gagne");
  GLADE_HOOKUP_OBJECT (window4_stat, button1_afficher_stat_gagne, "button1_afficher_stat_gagne");
  GLADE_HOOKUP_OBJECT (window4_stat, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window4_stat, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window4_stat, image13, "image13");
  GLADE_HOOKUP_OBJECT (window4_stat, label37, "label37");
  GLADE_HOOKUP_OBJECT (window4_stat, label36, "label36");

  return window4_stat;
}

