/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1gestionbv (void);
GtkWidget* create_window2ajouterbv (void);
GtkWidget* create_window3modifier__bv (void);
GtkWidget* create_window4_stat (void);
